var express = require("express")
var route = require("./Route.js")
var db = require("./dbcollection.js")
var parser = require("body-parser")
let cors=require('cors')

var app = express()
app.use(cors())
app.use(parser.json())
app.use("/",route)
app.listen(4500)